---
- name: Converge
  hosts: instance
  become: true
  vars:
    blocky__hosts_dns_enabled: true
    blocky__hosts_dns_host_ip_var: "ansible_host"
    blocky__hosts_dns_domain: ".local.example.com"
    blocky__blocking_blacklists: {}
    blocky__ports_dns: 127.0.0.1:5353
    blocky__cert_file: "/etc/cert/blocky_cert.pem"
    blocky__key_file: "/etc/cert/blocky_key.key"
    blocky__ports_https: 443
    blocky__ports_tls: 853
    blocky__custom_dns:
      app1.srv.example.com: 10.10.1.1
      one.local.example.com: 10.10.1.2
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family == "Debian"
      changed_when: false

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_facts.service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: ngine_io.blocky_dns
